### ISSUE TITLE
fix & clean-up ll_number external (C code)

### ISSUE THREAD

**Issue by jpsteccato** [ppooll-dev/ppooll#161]
general clean-up of code

bugs:
- [x] variable type for long comma positions (leli video)
- [x] when minimum value is 1, the object value still defaults to 0
- [x] object turns black when value is 0

new features:
- [x] object message "select" to give Max object focus (slider or number, whatever the default is in object attributes)

**Comment by jpsteccato** [comment]
fixed: `when minimum value is 1, the object value still defaults to 0`

when the object is initialized, all the values are initialized with the **slider_min** value.    
when more values are added (the **amount** of slider increases), values are also initialized with **slider_min** value.

when min and max attributes are changed, current slider values are constrained within the new range

**Comment by chausch** [comment]
hi joe, the issue i was experiencing is depicted in this short video demonstration here:

https://github.com/user-attachments/assets/1c7c8f1c-e089-46a8-bc37-d4d1dec52616

**Comment by chausch** [comment]
thanks for looking into this!!!

**Comment by jpsteccato** [comment]
@chausch thanks for all this :)  could you try this and let me know if this is what you want?  i think ll_number is outputting the correct floating point output based on keystrokes, but i needed to change the number of decimal places attribute of the regular max _number_ object

`<pre><code>
----------begin_max5_patcher----------
1052.3oc2XssiihCD84juBDOmMxku68s86n0pVNINYYFBf.xLcuil+801jjl
N3DfLzY1YjhHBSQcbcb4iKpuMeV7p7WLUwQ+YzSQyl8s4yl4GxMvri2OKdu9
k0o5JuYw555xCIwKZdT9g5TSc8qElFeDGG82GeTxFu84q9ze.jS1WnK06M0l
xmMY5Uo92Bc7YYG1mjY8lGG37KTu9eRx18boYccCFfDsTPnHJAgv.VxQvhHJ
VsDsHBXH2eX7Rz4IhaF6mJV.1XVmrWmVjpWaC62.tINZP1M32mO2cYw.Ikso
4VmbcRYQT7Jc1tfjiZHby17x8Ze7yGIaQIdBQg8zi.2gddeziuineuopRuyb
JNpMu3wNd0tsIooqySyKiXnsaYnwk1fQwgBV70CVhBVhuL0fHjKYBJkKIBJl
gIfZQjh2CQ.ePDAJByXQijI.1nYBIsKSfsICcXB.Q9oQEnQSD7QSDbnqZAAA
cIBo5CfGxLe0Nu6PCaLo5WitwFhqJW.hIgAvVkfNL.i93Xf5nM4eMKZUzpqx
ANCNKcdKITPFORUQBQEX6Af5xI793DxzwIUlT6LzlcFQfamYzhUByHzfLB45
LhMZ6xHff1kQDjO.FYH5EdgyQqX.ic+Bly+sT5bzmlhoAHhegkNoSBA7+.ky
CE2T27PwfTMIiUzLnDQPQSp5AJQ3B2QUV4nSCjh.kPvYARCP8kFbbzU676ia
7OZIPrtUB.fQJI25HzRkRgoLEE3DohJbCgvDNhIHJtRHApU+oENG8HdBc4tR
8lDSV86m3mEgd9DQG2DKArveElzn7BmeNdwJDn3HgjR.hf37DwBChnv.iK4X
QyPsLBy5w4G88B+ufloOTm2llbq+ArJaWymygEgMnnLuHurNIOqwID0zIW7Y
yqWc+QhcVuHzeAO.I39FzXKofPBtugcy8Mz6fORSe15jUlxwIOHG22i+jMER
c1OayypqR92lE62VqaJrqUNE3zIPstPEHlThILrcy.HaSCCTa14GhszEzkjq
8eupT6Tc27bqd8k8e4mXaPj76qOHsYb.urUv79d83dLq06jYwvC9eUlnSiuK
59bSmne.cU4tZzlZJazV3y8HAN26lscqkPW+cby+5woIYW1UR+7yM96orp7C
kqOwIm50XKw5Mlp5jL8Io0mdKYyYTvkkghj7QADL.fbev2ONPnAfDdJ.BdT.
4nEnOtSNUH0WHQlBfXOJti+n.RLjD7IYmjakF2GRroBodS7DSERCYYB9QAR8
fxGvOJYHxPxFfIBnGwRDY.IcSwAECQq6zgIcNbWWT7ESY0Qq8XXq74SMkFKW
3uMIq4VeUdwklujbxdeMbw5RawJ01JUNT1TE2K7lt6DuOeioLyV3TSgE1nyB
oupJWEeUEGK50W707uO++.b7tkhK
-----------end_max5_patcher-----------
</code></pre>
`

**Comment by chausch** [comment]
no, the problem is stilll there! it's really difficult to describe.

anyway 15 decimal places would be AWESOME to have in ll_number!

**Comment by chausch** [comment]
amazing, @jpsteccato – it seems the comma error is fixed! 🥳
